# Not the best makefile, but it's a start...
NAME=escheduler
CC=clang
CFLAGS=-Wall -std=gnu99 -o$(NAME)
LDFLAGS=
SOURCES=main.c timestuff.c commands.c

swrite :
	$(CC) $(LFLAGS) $(CFLAGS) $(SOURCES)

clean: 
	rm $(NAME)
